from enum import Enum

from models.card import Card
from models.suit import Suit


class Deck(Enum):
    ACE_OF_HEARTS = Card(1, Suit.HEARTS)
    TWO_OF_HEARTS = Card(2, Suit.HEARTS)
    THREE_OF_HEARTS = Card(3, Suit.HEARTS)
    FOUR_OF_HEARTS = Card(4, Suit.HEARTS)
    FIVE_OF_HEARTS = Card(5, Suit.HEARTS)
    SIX_OF_HEARTS = Card(6, Suit.HEARTS)
    SEVEN_OF_HEARTS = Card(7, Suit.HEARTS)
    EIGHT_OF_HEARTS = Card(8, Suit.HEARTS)
    NINE_OF_HEARTS = Card(9, Suit.HEARTS)
    TEN_OF_HEARTS = Card(10, Suit.HEARTS)
    JACK_OF_HEARTS = Card(11, Suit.HEARTS)
    QUEEN_OF_HEARTS = Card(12, Suit.HEARTS)
    KING_OF_HEARTS = Card(13, Suit.HEARTS)

    ACE_OF_SPADES = Card(1, Suit.SPADES)
    TWO_OF_SPADES = Card(2, Suit.SPADES)
    THREE_OF_SPADES = Card(3, Suit.SPADES)
    FOUR_OF_SPADES = Card(4, Suit.SPADES)
    FIVE_OF_SPADES = Card(5, Suit.SPADES)
    SIX_OF_SPADES = Card(6, Suit.SPADES)
    SEVEN_OF_SPADES = Card(7, Suit.SPADES)
    EIGHT_OF_SPADES = Card(8, Suit.SPADES)
    NINE_OF_SPADES = Card(9, Suit.SPADES)
    TEN_OF_SPADES = Card(10, Suit.SPADES)
    JACK_OF_SPADES = Card(11, Suit.SPADES)
    QUEEN_OF_SPADES = Card(12, Suit.SPADES)
    KING_OF_SPADES = Card(13, Suit.SPADES)

    ACE_OF_DIAMONDS = Card(1, Suit.DIAMONDS)
    TWO_OF_DIAMONDS = Card(2, Suit.DIAMONDS)
    THREE_OF_DIAMONDS = Card(3, Suit.DIAMONDS)
    FOUR_OF_DIAMONDS = Card(4, Suit.DIAMONDS)
    FIVE_OF_DIAMONDS = Card(5, Suit.DIAMONDS)
    SIX_OF_DIAMONDS = Card(6, Suit.DIAMONDS)
    SEVEN_OF_DIAMONDS = Card(7, Suit.DIAMONDS)
    EIGHT_OF_DIAMONDS = Card(8, Suit.DIAMONDS)
    NINE_OF_DIAMONDS = Card(9, Suit.DIAMONDS)
    TEN_OF_DIAMONDS = Card(10, Suit.DIAMONDS)
    JACK_OF_DIAMONDS = Card(11, Suit.DIAMONDS)
    QUEEN_OF_DIAMONDS = Card(12, Suit.DIAMONDS)
    KING_OF_DIAMONDS = Card(13, Suit.DIAMONDS)

    ACE_OF_CLUBS = Card(1, Suit.CLUBS)
    TWO_OF_CLUBS = Card(2, Suit.CLUBS)
    THREE_OF_CLUBS = Card(3, Suit.CLUBS)
    FOUR_OF_CLUBS = Card(4, Suit.CLUBS)
    FIVE_OF_CLUBS = Card(5, Suit.CLUBS)
    SIX_OF_CLUBS = Card(6, Suit.CLUBS)
    SEVEN_OF_CLUBS = Card(7, Suit.CLUBS)
    EIGHT_OF_CLUBS = Card(8, Suit.CLUBS)
    NINE_OF_CLUBS = Card(9, Suit.CLUBS)
    TEN_OF_CLUBS = Card(10, Suit.CLUBS)
    JACK_OF_CLUBS = Card(11, Suit.CLUBS)
    QUEEN_OF_CLUBS = Card(12, Suit.CLUBS)
    KING_OF_CLUBS = Card(13, Suit.CLUBS)

    JOKER = Card(20, None)
